<html  lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
<div class="container">
    <header>
        <h1>
            <a href="#">
                <img src="http://tfgms.com/sandbox/dailyui/logo-1.png" alt="Authentic Collection">
            </a>
        </h1>
    </header>
    <h1 class="text-center">Register</h1>
    <form method="POST">
        <label>
            <span class="label-text">Фамилия</span>
            <input type="text" name="lastname">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errors_inputs['lastname'] ?? ''; ?></span>
        </label>
        <label>
            <span class="label-text">Имя</span>
            <input type="text" name="firstname">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errors_inputs['firstname'] ?? ''; ?></span>
        </label>
        <label>
            <span class="label-text">Отчество</span>
            <input type="text" name="patronymic">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errors_inputs['patronymic']?? ''; ?></span>
        </label>
        <label>
            <span class="label-text">Email</span>
            <input type="text" name="email">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errors_inputs['email']?? ""; ?></span>
        </label>
        <label>
            <span class="label-text">Телефон</span>
            <input type="text" name="phonenumber">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errors_inputs['phonenumber']?? ""; ?></span>
        </label>
        <label class="password">
            <span class="label-text">Пароль</span>
            <input type="password" name="password">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errors_inputs['password']?? ""; ?></span>
        </label>
        <div class="text-center">
            <button class="submit" name="register">Зарегистрироваться</button>
        </div>
    </form>
</div>
</body>
</html>