<head>
    <meta charset="UTF-8">
    <title>Аутентификация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.3/animate.min.css'>

    <link rel="stylesheet" href="./forms/css/signinstyle.css">


</head>

<form method="POST">
<div class='box'>
    <div class='box-form'>
        <div class='box-login-tab'></div>
        <div class='box-login-title'>
            <div class='i i-login'></div><h2>Вход</h2>
        </div>
        <div class='box-login'>
            <div class='fieldset-body' id='login_form'>
                <button onclick="openLoginInfo();" class='b b-form i i-more' title='Mais Informações'></button>
                <p class='field'>
                    <label for='user'>Email</label>
                    <input type='text' id='user' name='email' title='Username'/>
                    <span class='label-text'><?php echo $errorInputs['email'] ?? ""; ?></span>
                </p>
                <p class='field'>
                    <label for='pass'>Пароль</label>
                    <input type='password' id='pass' name='password' title='Password' />
                    <span class='label-text'><?php echo $errorInputs['password'] ?? ""; ?></span>
                </p>

                <input type='submit' id='do_login' value='Войти' title='Get Started' />
            </div>
        </div>
    </div>
</div>
</form>