<main>
    <div class="background">
    </div>
    <article>

        <p class="fig">
            <img src="https://i.giphy.com/media/8L0Pky6C83SzkzU55a/giphy.webp" onerror="this.onerror=null;this.src='https://i.giphy.com/8L0Pky6C83SzkzU55a.gif';" alt="">
        </p>
        <p class="fig"  style="color: red" >Тут ничего нет</p>
    </article>
</main>
<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }
</style>