<form action="" method="GET">
    <div class="shopping-cart">
        <!-- Title -->
        <div class="title">
            Корзина
        </div>
        <?php /** @var CartProducts $cartProducts */
        use App\Entity\CartProducts;
        foreach ($cartProducts as $cartProduct): ?>
        <div class="item">
            <div class="buttons">
                <span class="delete-btn"></span>
                <span class="like-btn"></span>
            </div>

            <div class="image">
                <img src="<?= $cartProduct->getProduct()->getImage(); ?>" alt="" />
            </div>

            <div class="description">
                <span><?= $cartProduct->getProduct()->getName(); ?></span>
                <span><?= $cartProduct->getProduct()->getWeight(); ?></span>
                <span><?= $cartProduct->getProduct()->getPrice(); ?></span>
            </div>

            <div class="quantity">
                <button class="plus-btn" type="button" name="button">
                    <img src="plus.svg" alt="" />
                </button>
                <label>
                    <input type="text" name="name" value="<?= $cartProduct->getQuantity();?>">
                </label>
                <button class="minus-btn" type="button" name="button">
                    <img src="minus.svg" alt="" />
                </button>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</form>

<style>
    * {
        box-sizing: border-box;
    }

    html,
    body {
        width: 100%;
        height: 100%;
        margin: 0;
        background-color: #cb2d41;
        font-family: 'Roboto', sans-serif;
    }

    .shopping-cart {
        width: 750px;
        height: 423px;
        margin: 80px auto;
        background: #FFFFFF;
        box-shadow: 1px 2px 3px 0 rgba(0,0,0,0.10);
        border-radius: 6px;
        overflow: scroll;
        display: flex;
        flex-direction: column;
    }
    .title {
        height: 60px;
        border-bottom: 1px solid #E1E8EE;
        padding: 20px 30px;
        color: #5E6977;
        font-size: 18px;
        font-weight: 400;
    }

    .item {
        padding: 20px 30px;
        height: 120px;
        display: flex;
    }

    .item:nth-child(3) {
        border-top:  1px solid #E1E8EE;
        border-bottom:  1px solid #E1E8EE;
    }
    .buttons {
        position: relative;
        padding-top: 30px;
        margin-right: 60px;
    }
    .delete-btn,
    .like-btn {
        display: inline-block;
        Cursor: pointer;
    }
    .delete-btn {
        width: 18px;
        height: 17px;
        background: url("delete-icn.svg") no-repeat center;
    }

    .like-btn {
        position: absolute;
        top: 9px;
        left: 15px;
        background: url('twitter-heart.png');
        width: 60px;
        height: 60px;
        background-size: 2900%;
        background-repeat: no-repeat;
    }

    @keyframes animate {
        0%   { background-position: left;  }
        50%  { background-position: right; }
        100% { background-position: right; }
    }
    .image {
        margin-right: 50px;
    }
    .image img{
        max-width: 80px;
    }

    .description {
        padding-top: 10px;
        margin-right: 60px;
        width: 115px;
    }

    .description span {
        display: block;
        font-size: 14px;
        color: #43484D;
        font-weight: 400;
    }

    .description span:first-child {
        margin-bottom: 5px;
    }
    .description span:last-child {
        font-weight: 300;
        margin-top: 8px;
        color: #86939E;
    }
    .quantity {
        padding-top: 20px;
        margin-right: 60px;
    }
    .quantity input {
        -webkit-appearance: none;
        border: none;
        text-align: center;
        width: 32px;
        font-size: 16px;
        color: #43484D;
        font-weight: 300;
    }

    button[class*=btn] {
        width: 30px;
        height: 30px;
        background-color: #E1E8EE;
        border-radius: 6px;
        border: none;
        cursor: pointer;
    }
    .minus-btn img {
        margin-bottom: 3px;
    }
    .plus-btn img {
        margin-top: 2px;
    }

    button:focus,
    input:focus {
        outline:0;
    }


</style>
