<main>
    <div class="background">
    </div>
    <article>
        <p class="fig">
            <img src="https://i.giphy.com/media/0Dxuk20eU0bDYaxRR8/giphy.webp" onerror="this.onerror=null;this.src='https://i.giphy.com/0Dxuk20eU0bDYaxRR8.gif';" alt="">     </p>
        <p class="fig"  style="color: red" >Извините, ошибка сервера</p>
    </article>
</main>
<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }
</style>