<html  lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
    <style>
        @import url(https://fonts.googleapis.com/css?family=Cookie|Raleway:300,700,400);
        *{
            box-sizing: border-box;
            font-size: 1em;
            margin: 0;
            padding: 0;
        }
        body{
            background: url('http://tfgms.com/sandbox/dailyui/bg-1.jpg') center no-repeat;
            background-size: cover;
            color: #333;
            font-size: 18px;
            font-family: 'Raleway', sans-serif;
        }
        .container{
            border-radius: 0.5em;
            box-shadow: 0 0 1em 0 rgba(51,51,51,0.25);
            display: block;
            max-width: 480px;
            overflow: hidden;
            -webkit-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            padding: 2em;
            position: absolute;
            top: 50%;
            left: 50%;
            z-index: 1;
            width: 98%;
        }
        .container:before{
            background: url('http://tfgms.com/sandbox/dailyui/bg-1.jpg') center no-repeat;
            background-size: cover;
            content: '';
            -webkit-filter: blur(10px);
            filter: blur(10px);
            height: 100vh;
            position: absolute;
            top: 50%;
            left: 50%;
            z-index: -1;
            -webkit-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            width: 100vw;
        }
        .container:after{
            background: rgba(255,255,255,0.6);
            content: '';
            display: block;
            height: 100%;
            position: absolute;
            top: 0;
            left: 0;
            z-index: -1;
            width: 100%;
        }
        form button.submit{
            background: rgba(255,255,255,0.25);
            border: 1px solid #333;
            line-height: 1em;
            padding: 0.5em 0.5em;
            -webkit-transition: all 0.25s;
            transition: all 0.25s;
        }
        form button:hover,
        form button:focus,
        form button:active,

        @-webkit-keyframes spin{
            from{ transform: rotate(0deg); }
            to{ transform: rotate(360deg); }
        }
        @keyframes spin{
            from{ transform: rotate(0deg); }
            to{ transform: rotate(360deg); }
        }


        form label{
            border-bottom: 1px solid #333;
            display: block;
            font-size: 1.25em;
            margin-bottom: 0.5em;
            -webkit-transition: all 0.25s;
            transition: all 0.25s;
        }

        form label input{
            background: none;
            border: none;
            line-height: 1em;
            font-weight: 300;
            padding: 0.125em 0.25em;
            width: 100%;
        }
        form label input:focus{
            outline: none;
        }
        form label input:-webkit-autofill{
            background-color: transparent !important;
        }
        form label span.label-text{
            display: block;
            font-size: 0.5em;
            font-weight: bold;
            padding-left: 0.5em;
            text-transform: uppercase;
            -webkit-transition: all 0.25s;
            transition: all 0.25s;
        }

        form label.checkbox input{
            display: none;
        }
        form label.checkbox span{
            font-size: 0.5em;
        }
        form label.checkbox span:before{
            content: '\e157';
            display: inline-block;
            font-family: 'Glyphicons Halflings';
            font-size: 1.125em;
            padding-right: 0.25em;
            position: relative;
            top: 1px;
        }
        form label.checkbox input:checked + span:before{content: '\e067';}
        form label.invalid{border-color: dimgrey !important;}
        form label.invalid span.label-text{color: #df405a;}
        form label.password{position: relative;}


        form label.password button.toggle-visibility span{vertical-align: middle;}

        h1{
            font-size: 3em;
            margin: 0 0 0.5em 0;
            text-align: center;
            font-family: 'Cookie', cursive;
        }
        h1 img{
            height: auto;
            margin: 0 auto;
            max-width: 240px;
            width: 100%;
        }
        html{
            font-size: 18px;
            height: 100%;
        }

        .text-center{
            text-align: center;
        }
    </style>
</head>
<body>
<div class="container">
    <header>
        <h1>
            <a href="#">
                <img src="http://tfgms.com/sandbox/dailyui/logo-1.png" alt="Authentic Collection">
            </a>
        </h1>
    </header>
    <h1 class="text-center">Register</h1>
    <form method="POST">
        <label>
            <span class="label-text">Фамилия</span>
            <input type="text" name="lastname">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errorInputs['lastname'] ?? ''; ?>
            </span>
        </label>
        <label>
            <span class="label-text">Имя</span>
            <input type="text" name="firstname">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errorInputs['firstname'] ?? ''; ?></span>
        </label>
        <label>
            <span class="label-text">Отчество</span>
            <input type="text" name="patronymic">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errorInputs['patronymic']?? ''; ?></span>
        </label>
        <label>
            <span class="label-text">Email</span>
            <input type="text" name="email">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errorInputs['email']?? ""; ?></span>
        </label>
        <label>
            <span class="label-text">Телефон</span>
            <input type="text" name="phoneNumber">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errorInputs['phoneNumber']?? ""; ?></span>
        </label>
        <label class="password">
            <span class="label-text">Пароль</span>
            <input type="password" name="password">
        </label>
        <label class="invalid">
            <span class="label-text"><?php echo $errorInputs['password']?? ""; ?></span>
        </label>
        <div class="text-center">
            <button class="submit" name="register">Зарегистрироваться</button>
        </div>
    </form>
</div>
</body>
</html>